From node:14.17.5-alpine
WORKDIR /app
COPY . .
RUN yarn install
CMD ['yarn', 'run', 'dev']

github mono repo

repo 1 => domain.com/1
repo 2 => domain.com/2 
repo 3 => domain.com/3

push master => domain.com/1

exec git init => git commit => git push 



